---
- name: Generate hosts file in localhost for all ecs instances
  hosts: localhost
  tasks:
    - name: Copy hosts file
      command: cp /etc/hosts hosts
    - name: Update ecs IPs in hosts file
      lineinfile:
        dest: hosts
        regexp: "^{{ hostvars[item].aliyun.PublicIp | replace('.', '\\.') }}"
        line: "{{ hostvars[item].aliyun.PublicIp }} {{ item }}.aliyun"
      with_items: groups.ecs
    - debug: msg="Copy hosts to overwrite your /etc/hosts"
- name: Generate hosts file in all ecs instances
  hosts: ecs
  sudo: true
  tasks:
    - name: Update ecs IPs in hosts file
      lineinfile:
        dest: /etc/hosts
        regexp: "^{{ hostvars[item].aliyun.PublicIp | replace('.', '\\.') }}"
        line: "{{ hostvars[item].aliyun.PublicIp }} {{ item }}.aliyun"
      with_items: groups.ecs
    - name: Update ecs private IPs in hosts file
      lineinfile:
        dest: /etc/hosts
        regexp: "^{{ hostvars[item].aliyun.InnerIp | replace('.', '\\.') }}"
        line: "{{ hostvars[item].aliyun.InnerIp }} {{ item }}.private"
      with_items: groups.ecs
